---
# Copyright (C) 2023 David Härdeman <david@hardeman.nu>
# Copyright (C) 2023 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Import DebOps global handlers
  ansible.builtin.import_role:
    name: 'global_handlers'

- name: Make sure that the cache directory exists
  ansible.builtin.file:
    path: '{{ cachefilesd__directory }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  tags: [ 'role::cachefilesd:install' ]

- name: Divert the configuration file
  debops.debops.dpkg_divert:
    path: '/etc/cachefilesd.conf'
    state: 'present'
    delete: True
  tags: [ 'role::cachefilesd:config' ]

- name: Create configuration file and systemd unit
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - 'etc/cachefilesd.conf'
    - 'etc/systemd/system/cachefilesd.service'
  loop_control:
    label: '{{ "/" + item }}'
  notify: [ 'Restart cachefilesd service' ]
  tags: [ 'role::cachefilesd:config' ]

- name: Install required packages
  ansible.builtin.package:
    name: '{{ (cachefilesd__base_packages + cachefilesd__packages) | flatten }}'
    state: 'present'
  register: cachefilesd__register_packages
  until: cachefilesd__register_packages is succeeded
  tags: [ 'role::cachefilesd:install' ]

- name: Ensure that the cachefilesd service is enabled and started
  ansible.builtin.systemd:
    name: 'cachefilesd.service'
    daemon_reload: True
    enabled: True
    state: 'started'

- name: Make sure that Ansible local facts directory exists
  ansible.builtin.file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    mode: '0755'

- name: Save cachefilesd local facts
  ansible.builtin.template:
    src: 'etc/ansible/facts.d/cachefilesd.fact.j2'
    dest: '/etc/ansible/facts.d/cachefilesd.fact'
    mode: '0755'
  notify: [ 'Refresh host facts' ]
  tags: [ 'meta::facts' ]

- name: Flush handlers
  ansible.builtin.meta: 'flush_handlers'
