---
# Copyright (C) 2013-2017 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2023 David Härdeman <david@hardeman.nu>
# Copyright (C) 2015-2023 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Manage NFS shares
  collections: [ 'debops.debops', 'debops.roles01',
                 'debops.roles02', 'debops.roles03' ]
  hosts: [ 'debops_service_nfs' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: cachefilesd
      tags: [ 'role::cachefilesd', 'skip::cachefilesd' ]
      when: nfs__cache | d(False) | bool

    - role: ldap
      tags: [ 'role::ldap', 'skip::ldap' ]
      ldap__dependent_tasks:
        - '{{ nfs__ldap__dependent_tasks }}'

    - role: kerberos
      tags: [ 'role::kerberos', 'skip::kerberos' ]
      kerberos__dependent_tasks:
        - '{{ nfs__kerberos__dependent_tasks }}'

    - role: nfs
      tags: [ 'role::nfs', 'skip::nfs' ]
