---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2013-2017 Maciej Delmanowski <drybjed@gmail.com>
# .. Copyright (C) 2023 David Härdeman <david@hardeman.nu>
# .. Copyright (C) 2015-2023 DebOps <https://debops.org/>
# .. SPDX-License-Identifier: GPL-3.0-only

# .. _nfs__ref_defaults:

# debops.nfs default variables [[[
# ================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../../includes/global.rst


# APT packages [[[
# ----------------

# .. envvar:: nfs__base_packages [[[
#
# List of APT packages that are required for NFS support.
nfs__base_packages: [ 'nfs-common' ]

                                                                   # ]]]
# .. envvar:: nfs__packages [[[
#
# List of additional APT packages to install with NFS support.
nfs__packages: []

                                                                   # ]]]
                                                                   # ]]]
# NFS mount configuration [[[
# ---------------------------

# .. envvar:: nfs__kerberos [[[
#
# Enable Kerberos support.
nfs__kerberos: '{{ ansible_local.kerberos.enabled | d(False) }}'

                                                                   # ]]]
# .. envvar:: nfs__kerberos_princ [[[
#
# The Kerberos principal for the nfs service.
nfs__kerberos_princ: '{{ "nfs/" + ansible_fqdn + "@"
                         + (ansible_local.kerberos.default_realm |
                            d(nfs__kerberos_realms | list | first | upper)) }}'

                                                                   # ]]]
# .. envvar:: nfs__kerberos_realms [[[
#
# List or string with local Kerberos realms.
nfs__kerberos_realms: '{{ ansible_local.kerberos.default_realm
                          | d(ansible_domain) | upper }}'

                                                                   # ]]]
# .. envvar:: nfs__cache [[[
#
# Enable local filesystem cacheing using :ref:`debops.cachefilesd`.
nfs__cache: False

                                                                   # ]]]
# .. envvar:: nfs__domain [[[
#
# The local NFSv4 domain name. An NFSv4 domain is a namespace with a unique
# username<->UID and groupname<->GID mapping. The NFSv4 domain is therefore
# separate from the actual server domain or Kerberos realm(s). The default
# should be fine for most users.
nfs__domain: '{{ ansible_local.kerberos.default_realm
                 | d(ansible_domain) | lower }}'

                                                                   # ]]]
# .. envvar:: nfs__default_mount_type [[[
#
# The default filesystem type used for NFS mount points, if a custom type is
# not specified in the NFS share configuration.
nfs__default_mount_type: 'nfs4'

                                                                   # ]]]
# .. envvar:: nfs__base_mount_options [[[
#
# List of :command:`mount` options that are added to all mount points
# configured by this role. These should ensure correct operation for a network
# mount point.
nfs__base_mount_options:

  - 'proto=tcp'
  - 'port=2049'
  - '_netdev'
  - 'x-systemd.after=named.service'
  - 'x-systemd.after=pdns.service'
  - 'x-systemd.automount'

                                                                   # ]]]
# .. envvar:: nfs__security_mount_options [[[
#
# List of :command:`mount` options related to Kerberos security, added to all
# mount points configured by this role.
nfs__security_mount_options: '{{ ["sec=krb5p", "x-systemd.after=rpc-gssd.service"]
                                 if nfs__kerberos | bool
                                 else ["sec=sys"] }}'

                                                                   # ]]]
# .. envvar:: nfs__cache_mount_options [[[
#
# List of :command:`mount` options related to local caching, added to all
# mount points configured by this role.
nfs__cache_mount_options: '{{ ["fsc"] if nfs__cache | bool else [] }}'

                                                                   # ]]]
# .. envvar:: nfs__default_mount_options [[[
#
# List of default :command:`mount` options added to all mount point configured
# by this role if no options are specified in the configuration of a given NFS
# share.
nfs__default_mount_options: [ 'noatime', 'nosuid', 'nodev', 'hard' ]

                                                                   # ]]]
                                                                   # ]]]
# NFS shares [[[
# --------------

# The lists of NFS shares configured on the hosts. Each list element is
# a dictionary which describes an NFS share. See :ref:`nfs__ref_shares` for
# more details.

# .. envvar:: nfs__shares [[[
#
# List of NFS shares configured on all hosts in the Ansible inventory.
nfs__shares: []

                                                                   # ]]]
# .. envvar:: nfs__group_shares [[[
#
# List of NFS shares configured on hosts in specific Ansible inventory group.
nfs__group_shares: []

                                                                   # ]]]
# .. envvar:: nfs__host_shares [[[
#
# List of NFS shares configured on specific hosts in the Ansible inventory.
nfs__host_shares: []

                                                                   # ]]]
# LDAP environment [[[
# --------------------

# .. envvar:: nfs__ldap_device_dn [[[
#
# The Distinguished Name of the current host LDAP object, defined as a YAML
# list. It will be used as a base for the NFS service account LDAP object. If
# the list is empty, the role will not create the account LDAP object
# automatically.
nfs__ldap_device_dn: '{{ ansible_local.ldap.device_dn | d([]) }}'

                                                                   # ]]]
# .. envvar:: nfs__ldap_self_rdn [[[
#
# The Relative Distinguished Name of the account LDAP object used by the NFS
# service.
nfs__ldap_self_rdn: 'uid=nfs'

                                                                   # ]]]
# .. envvar:: nfs__ldap_self_object_classes [[[
#
# List of the LDAP object classes which will be used to create the LDAP object
# used by the NFS service.
nfs__ldap_self_object_classes: [ 'account', 'krbPrincipalAux' ]

                                                                   # ]]]
# .. envvar:: nfs__ldap_self_attributes [[[
#
# YAML dictionary that defines the attributes of the LDAP object used by the
# NFS service.
nfs__ldap_self_attributes:
  uid: '{{ nfs__ldap_self_rdn.split("=")[1] }}'
  host: '{{ [ ansible_fqdn, ansible_hostname ] | unique }}'
  description: 'Account used by the "nfs" service to store its Kerberos principal'

                                                                   # ]]]
# .. envvar:: nfs__ldap_self_dn [[[
#
# The Distinguished Name of the account LDAP object used by the NFS service.
nfs__ldap_self_dn: '{{ ([ nfs__ldap_self_rdn ] + nfs__ldap_device_dn) | join(",") }}'

                                                                   # ]]]
                                                                   # ]]]
# Configuration for other Ansible roles [[[
# -----------------------------------------

# .. envvar:: nfs__ldap__dependent_tasks [[[
#
# Configuration for the :ref:`debops.ldap` Ansible role.
nfs__ldap__dependent_tasks:

  - name: 'Create nfs account for {{ nfs__ldap_device_dn | join(",") }}'
    dn: '{{ nfs__ldap_self_dn }}'
    objectClass: '{{ nfs__ldap_self_object_classes }}'
    attributes: '{{ nfs__ldap_self_attributes }}'
    state: '{{ "present" if nfs__ldap_device_dn | d() else "ignore" }}'

                                                                   # ]]]
# .. envvar:: nfs__kerberos__dependent_tasks [[[
#
# Configuration for the :ref:`debops.kerberos` Ansible role.
nfs__kerberos__dependent_tasks:
  - name: 'Ensure that the Kerberos principal {{ nfs__kerberos_princ }} exists'
    principal: '{{ nfs__kerberos_princ }}'
    path: '/etc/krb5.keytab.d/nfs.keytab'
    mode: '0640'
    owner: 'root'
    group: 'root'
    state: '{{ "present" if (nfs__kerberos | d(False)) else "ignore" }}'
    ldap_dn: '{{ nfs__ldap_self_dn if nfs__ldap_device_dn | d() else omit }}'

                                                                   # ]]]
                                                                   # ]]]
                                                                   # ]]]
